### ISSUE TITLE
Reference the same version of the action not the main

### ISSUE THREAD

**Issue by dcalavrezo-qorix** [eclipse-score/cicd-workflows#18]
```
      - name: Deploy 🚀
        id: pages-deployment
        uses: eclipse-score/cicd-workflows/.github/actions/deploy-versioned-pages@main
        with:
          source_folder: extracted_docs/html

```

We shouldn't reference `main`, but `workflow-version`

There's a GH Actions limitation though, for which this ticket exists
