### ISSUE TITLE
Support configurable runs-on label in reusable workflows

### ISSUE THREAD

**Issue by dcalavrezo-qorix** [eclipse-score/cicd-workflows#29]
At the moment, all jobs use the default runner label:

```
runs-on: ubuntu-latest
```

However, we’d like to allow repositories to choose their runner label, such as self-hosted, arm64-runner or other custom labels.

It's fine using a matrix workaround since direct input is not supported for `runs-on`

```
strategy:
  matrix:
    runner: [${{ inputs.runner-label }}]
runs-on: ${{ matrix.runner }}

```
